# Generated by Django 5.1.3 on 2024-12-06 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("forum", "0002_remove_category_parent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                related_name="tagged_posts", through="forum.PostTag", to="forum.tag"
            ),
        ),
    ]
