name: Jackson Park
url: https://jacksonparklic.com/availability
parser_type: html
building_info:
  name: Jackson Park
  address: "28-34 Jackson Avenue"
  postal_code: "11101"
  city: Long Island City
  state: NY
  website: https://jacksonparklic.com
  amenities:
    fitness_center: true
    pool: true
    lounge: true
    doorman: true

selectors:
  unit_list: ".availibility-box"
  unit_data:
    unit_number: ".box-title"
    tower: ".tower-title"
    bedrooms: ".property-details"
    bathrooms: ".property-details"
    price: ".property-details:contains('$')"

transformers:
  bedrooms: extract_bedrooms_from_details
  bathrooms: extract_bathrooms_from_details
  price: extract_price_from_details