# Generated by Django 5.1.3 on 2024-11-26 21:16

import buildings.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ScrapingRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.DateTimeField()),
                ("end_time", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("items_processed", models.IntegerField(default=0)),
                ("items_created", models.IntegerField(default=0)),
                ("items_updated", models.IntegerField(default=0)),
                ("items_errored", models.IntegerField(default=0)),
                ("error_log", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ScrapingSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("base_url", models.URLField(max_length=500)),
                ("is_active", models.BooleanField(default=True)),
                ("scraping_frequency_hours", models.IntegerField(default=24)),
                ("scraping_config", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Building",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("address", models.CharField(max_length=500)),
                ("postal_code", models.CharField(max_length=10)),
                ("city", models.CharField(max_length=100)),
                ("state", models.CharField(max_length=50)),
                (
                    "latitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                (
                    "longitude",
                    models.DecimalField(decimal_places=6, max_digits=9, null=True),
                ),
                ("website", models.URLField(max_length=500)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("year_built", models.IntegerField(blank=True, null=True)),
                ("amenities", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["postal_code"], name="buildings_b_postal__5fddbd_idx"
                    ),
                    models.Index(
                        fields=["city", "state"], name="buildings_b_city_9d7dbc_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Apartment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("unit_number", models.CharField(max_length=20)),
                ("floor", models.IntegerField()),
                ("bedrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("bathrooms", models.DecimalField(decimal_places=1, max_digits=3)),
                ("area_sqft", models.IntegerField()),
                ("apartment_type", models.CharField(max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("pending", "Pending"),
                            ("leased", "Leased"),
                            ("unavailable", "Unavailable"),
                        ],
                        default="available",
                        max_length=20,
                    ),
                ),
                ("features", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "building",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="apartments",
                        to="buildings.building",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="NewUserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=15, null=True),
                ),
                (
                    "preferred_contact_method",
                    models.CharField(
                        choices=[("email", "Email"), ("phone", "Phone")],
                        default="email",
                        max_length=10,
                    ),
                ),
                ("notification_preferences", models.JSONField(default=dict)),
                ("saved_searches", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            managers=[
                ("objects", buildings.models.NewUserManager()),
            ],
        ),
        migrations.CreateModel(
            name="PriceChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("old_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("new_price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="buildings.apartment",
                    ),
                ),
                (
                    "scraping_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_changes",
                        to="buildings.scrapingrun",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="scrapingrun",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="runs",
                to="buildings.scrapingsource",
            ),
        ),
        migrations.CreateModel(
            name="ApartmentPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(blank=True, null=True)),
                ("lease_term_months", models.IntegerField()),
                ("is_special_offer", models.BooleanField(default=False)),
                ("special_offer_details", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "apartment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_history",
                        to="buildings.apartment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["start_date"], name="buildings_a_start_d_3196cb_idx"
                    ),
                    models.Index(fields=["price"], name="buildings_a_price_645bb9_idx"),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(fields=["status"], name="buildings_a_status_5d9839_idx"),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["bedrooms"], name="buildings_a_bedroom_214742_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="apartment",
            index=models.Index(
                fields=["area_sqft"], name="buildings_a_area_sq_6f0d8e_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="apartment",
            unique_together={("building", "unit_number")},
        ),
        migrations.AddIndex(
            model_name="pricechange",
            index=models.Index(
                fields=["detected_at"], name="buildings_p_detecte_dc180a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingrun",
            index=models.Index(
                fields=["start_time"], name="buildings_s_start_t_7a77a2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="scrapingrun",
            index=models.Index(fields=["status"], name="buildings_s_status_aa2b7f_idx"),
        ),
    ]
