# Generated by Django 5.1.3 on 2024-12-11 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="region",
            name="neighborhood",
            field=models.CharField(
                choices=[
                    ("LES", "Lower East Side"),
                    ("FID", "Financial District"),
                    ("HEL", "Hell's Kitchen"),
                    ("CHE", "Chelsea"),
                    ("UES", "Upper East Side"),
                    ("UWS", "Upper West Side"),
                    ("HAR", "Harlem"),
                    ("GRV", "Greenwich Village"),
                    ("SOH", "SoHo"),
                    ("TRI", "Tribeca"),
                    ("MTW", "Midtown West"),
                    ("MTE", "Midtown East"),
                    ("LIC", "Long Island City"),
                    ("AST", "Astoria"),
                    ("FLU", "Flushing"),
                    ("WBG", "Williamsburg"),
                    ("DUM", "DUMBO"),
                    ("DTB", "Downtown Brooklyn"),
                    ("BRH", "Brooklyn Heights"),
                    ("JCC", "Jersey City"),
                    ("HOB", "Hoboken"),
                    ("UNC", "Union City"),
                ],
                max_length=3,
            ),
        ),
    ]
