# Generated by Django 5.1.3 on 2024-12-03 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0004_alter_newuserprofile_managers_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricechange",
            name="scraping_run",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="price_changes",
                to="buildings.scrapingrun",
            ),
        ),
    ]
