# Generated by Django 5.1.3 on 2024-12-03 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("buildings", "0005_alter_pricechange_scraping_run"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="newuserprofile",
            name="buildings_n_created_e02036_idx",
        ),
        migrations.RemoveIndex(
            model_name="newuserprofile",
            name="buildings_n_phone_n_227888_idx",
        ),
        migrations.RemoveField(
            model_name="newuserprofile",
            name="notification_preferences",
        ),
        migrations.RemoveField(
            model_name="newuserprofile",
            name="saved_searches",
        ),
        migrations.AddField(
            model_name="newuserprofile",
            name="apartment_preferences",
            field=models.JSONField(default=dict),
        ),
    ]
