# Generated by Django 5.1.3 on 2024-12-05 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "buildings",
            "0006_remove_newuserprofile_buildings_n_created_e02036_idx_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "borough",
                    models.CharField(
                        choices=[
                            ("MAN", "Manhattan"),
                            ("BRK", "Brooklyn"),
                            ("QNS", "Queens"),
                            ("BRX", "Bronx"),
                            ("NJ", "New Jersey"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "neighborhood",
                    models.CharField(
                        choices=[
                            ("LES", "Lower East Side"),
                            ("FID", "Financial District"),
                            ("HEL", "Hell's Kitchen"),
                            ("CHE", "Chelsea"),
                            ("UES", "Upper East Side"),
                            ("UWS", "Upper West Side"),
                            ("HAR", "Harlem"),
                            ("GRV", "Greenwich Village"),
                            ("SOH", "SoHo"),
                            ("TRI", "Tribeca"),
                            ("LIC", "Long Island City"),
                            ("AST", "Astoria"),
                            ("FLU", "Flushing"),
                            ("WBG", "Williamsburg"),
                            ("DUM", "DUMBO"),
                            ("DTB", "Downtown Brooklyn"),
                            ("BRH", "Brooklyn Heights"),
                            ("JCC", "Jersey City"),
                            ("HOB", "Hoboken"),
                            ("UNC", "Union City"),
                        ],
                        max_length=3,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["borough"], name="buildings_r_borough_96d211_idx"
                    ),
                    models.Index(
                        fields=["neighborhood"], name="buildings_r_neighbo_254bbc_idx"
                    ),
                ],
                "unique_together": {("borough", "neighborhood")},
            },
        ),
        migrations.AddField(
            model_name="building",
            name="region",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="buildings",
                to="buildings.region",
            ),
        ),
        migrations.AddIndex(
            model_name="building",
            index=models.Index(
                fields=["region"], name="buildings_b_region__171609_idx"
            ),
        ),
    ]
